### ISSUE TITLE
gen/enums.h

### ISSUE THREAD

**Issue by zeiksz** [TESSkyblivion/skyblivion-niflib#7]
While compiling it is missing gen/enums.h.
> Cannot open include file: 'gen/enums.h': No such file or directory	hkxcmd	...path...\skyblivion-niflib\include\nif_basic_types.h

**Comment by aerisarn** [comment]
That file gets generated, among the others, by the python script that is run before the compilation. CMake should select the right python version (2.7) and run the generation, but sometimes python 3 gets selected anyway and the generation fails. Please verify that you have a python 2 interpreter in path and that CMake correctly selects it
